api/urls.py
from django.urls import re_path as url
from api.views import ReportsListAPIView, ReportsDetailAPIView, CatalogsListView, CatalogsDetailAPIView, ManifestsListView, ManifestsDetailAPIView, PkgsinfoListView, PkgsinfoDetailAPIView, PkgsListView, PkgsDetailAPIView, IconsListView, IconsDetailAPIView

urlpatterns = [
    url(r'^reports/?$', ReportsListAPIView.as_view(), name="report-list"),
    url(r'^reports/(?P<serial_number>[a-zA-Z0-9]+)$', ReportsDetailAPIView.as_view(), name="report-detail"),
    url(r'^catalogs/?$', CatalogsListView.as_view(), name="catalog-list"),
    url(r'^catalogs/(?P<filepath>.*$)', CatalogsDetailAPIView.as_view(), name="catalog-detail"),
    url(r'^manifests/?$', ManifestsListView.as_view(), name="manifest-list"),
    url(r'^manifests/(?P<filepath>.*$)', ManifestsDetailAPIView.as_view()),
    url(r'^pkgsinfo/?$', PkgsinfoListView.as_view(), name="pkgsinfo-list"),
    url(r'^pkgsinfo/(?P<filepath>.*$)', PkgsinfoDetailAPIView.as_view(), name="pkgsinfo-detail"),
    url(r'^pkgs/?$', PkgsListView.as_view(), name="pkgs-list"),
    url(r'^pkgs/(?P<filepath>.*$)', PkgsDetailAPIView.as_view(), name="pkgs-download"),
    url(r'^icons/?$', IconsListView.as_view(), name="icon-list"),
    url(r'^icons/(?P<filepath>.*$)', IconsDetailAPIView.as_view(), name="icon-download"),
]

munkiwebadmin/urls.py
from django.urls import re_path as url
from django.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from  django.contrib.auth.views import LoginView, logout_then_login
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

from django.contrib import admin
admin.autodiscover()

import os
try:
	BASE_DIR = settings.BASE_DIR
except:
	BASE_DIR = ""
      
try:
	REPO_MANAGEMENT_ONLY = settings.REPO_MANAGEMENT_ONLY
except:
	REPO_MANAGEMENT_ONLY = False

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^oauth2/', include('django_auth_adfs.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^manifests/', include('manifests.urls')),
    url(r'^reports/', include('reports.urls')),
    url(r'^catalogs/', include('catalogs.urls')),
    url(r'^pkgsinfo/', include('pkgsinfo.urls')),
    url(r'^icons/', include('icons.urls')),
    url(r'^inventory/', include('inventory.urls')),
    url(r'^santa/', include('santa.urls')),
    url(r'^makecatalogs/', include('process.urls')),
]

if REPO_MANAGEMENT_ONLY:
    urlpatterns.append(url(r'^$', RedirectView.as_view(url='/manifests/')))
else:
    urlpatterns.append(url(r'^$', RedirectView.as_view(url='/reports/')))

# comment out the following if you are serving
# static files a different way
urlpatterns += staticfiles_urlpatterns()

# debug/development serving MEDIA files (icons)
try:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
except django.core.exceptions.ImproperlyConfigured:
    print("**** MEDIA_URL or MEDIA_ROOT missing from settings.py       ****")
    print("**** copy MEDIA_URL or MEDIA_ROOT from settings_template.py ****")
    raise

pkgsinfo/urls.py
from django.urls import re_path as url
import pkgsinfo.views

urlpatterns = [
    url(r'^$', pkgsinfo.views.index, name='pkginfo'),
    url(r'^__get_process_status$', pkgsinfo.views.status),
    url(r'^_json$', pkgsinfo.views.getjson),
    url(r'^(?P<pkginfo_path>^.*$)', pkgsinfo.views.detail)
]

pkgsinfo/models.py
"""
pkgsinfo/models.py
"""

from django.db import models
import os
import logging
import plistlib
import functools
from collections import defaultdict
from distutils.version import LooseVersion
from multiprocessing.pool import ThreadPool
from xml.parsers.expat import ExpatError

from django.conf import settings
from process.utils import record_status
from catalogs.models import Catalog
from api.models import MunkiRepo, \
                       FileReadError, FileWriteError, FileDeleteError

PKGSINFO_STATUS_TAG = 'pkgsinfo_list_process'
LOGGER = logging.getLogger('munkiwebadmin')

def pkg_ref_count(pkginfo_path, catalog_items):
    '''Returns the number of pkginfo items containing a reference to
    the installer_item_location in pkginfo_path and the relative path to
    the installer_item_location'''
    try:
        plistdata = MunkiRepo.read('pkgsinfo', pkginfo_path)
    except FileReadError:
        return 0, ''
    
    pkg_path = plistdata.get('installer_item_location')
    if not pkg_path:
        return 0, ''
    matching_count = 0
    if catalog_items:
        matches = [item for item in catalog_items
                   if item.get('installer_item_location') == pkg_path]
        matching_count = len(matches)
    return matching_count, pkg_path


def process_file(pkginfo_path):
    '''Worker function called by our multiprocessing pool. Reads a pkginfo
    file and returns a tuple of name, version, catalogs, and relative path'''
    try:
        pkginfo = MunkiRepo.read('pkgsinfo', pkginfo_path)
    except (ExpatError, IOError):
        return ()
    return (pkginfo.get('name', 'NO_NAME'),
            pkginfo.get('display_name', 'NO_DISPLAY_NAME'),
            pkginfo.get('version', 'NO_VERSION'),
            pkginfo.get('catalogs', []),
            pkginfo_path)


def any_files_in_list_newer_than(files, filepath):
    '''Returns true if any file in the list of files
    is newer that filepath'''
    # todo: needs to be fixed
    '''try:
        mtime = os.stat(filepath).st_mtime
    except OSError:
        return True
    for fname in files:
        fullpath = os.path.join(PKGSINFO_PATH, fname)
        if os.stat(fullpath).st_mtime > mtime:
            return True'''
    return False


def record(message=None, percent_done=None):
    '''Record a status message for a long-running process'''
    record_status(
        PKGSINFO_STATUS_TAG, message=message, percent_done=percent_done)


class PkginfoFile(models.Model):
    '''Placeholder so we get permissions entries in the admin database'''
    pass


class Pkginfo(MunkiRepo):
    '''Models pkginfo items'''
    @classmethod
    def data(cls):
        '''Returns a structure with itemnames, versions, and filepaths'''
        def cmp(a, b):
            try:
                return (a > b) - (a < b)
            except TypeError:
                return 1

        def compare_versions(a, b):
            """Internal comparison function for use in sorting"""
            return cmp(LooseVersion(b[0]), LooseVersion(a[0]))
        record(message='Starting scan of pkgsinfo data')
        files = cls.list('pkgsinfo')
        record(message='Processing %s files' % len(files))
        all_items = cls.read('catalogs', 'all')
        use_slower_approach = False
        if len(all_items) != len(files):
            LOGGER.debug('number of files differ from all catalog')
            use_slower_approach = True
        #elif any_files_in_list_newer_than(files, all_catalog):
        #    LOGGER.debug('files newer than all catalog')
        #    use_slower_approach = True
        pkginfo_dict = defaultdict(list)
        record(message='Assembling pkgsinfo data')
        if use_slower_approach:
            LOGGER.debug("using slower approach")
            # read the individual pkgsinfo files but use four threads
            # to speed things up a bit since we wait a lot for I/O
            pool = ThreadPool(processes=4)
            tuples = pool.map(process_file, files)
            for name, display_name, version, catalogs, pathname in tuples:
                pkginfo_dict[name].append((version, catalogs, pathname, display_name))
        else:
            LOGGER.debug("using faster approach")
            # use the data in the all catalog; one file read instead
            # of hundreds or thousands
            for index, item in enumerate(all_items):
                name = item.get('name', 'NO_NAME')
                version = item.get('version', 'NO_VERSION')
                catalogs = item.get('catalogs', [])
                pathname = files[index]
                pkginfo_dict[name].append((version, catalogs, pathname))
        for key in pkginfo_dict.keys():
            pkginfo_dict[key].sort(key=functools.cmp_to_key(compare_versions))
        LOGGER.debug('Sorted pkgsinfo dict')

        # now convert to a list of lists
        pkginfo_list = []
        for key, value in pkginfo_dict.items():
            pkginfo_list.append([key, value])
        LOGGER.debug('Converted to tuple')
        record(message='Completed assembly of pkgsinfo data')
        return pkginfo_list

    @classmethod
    def mass_delete(cls, pathname_list, user, delete_pkgs=False):
        '''Deletes pkginfo files from a list and optionally deletes the
        associated installer items (pkgs)'''
        errors = []
        catalog_items = []
        if delete_pkgs:
            # cache the catalog_items once; we don't want to incur the
            # overhead of reading the 'all' catalog multiple times
            catalog_items = Catalog.detail('all')

        for pathname in pathname_list:
            delete_this_pkg = False
            if delete_pkgs:
                ref_count, pkg_path = pkg_ref_count(pathname, catalog_items)
                if ref_count == 1:
                    # OK to delete the pkg if there is only one pkginfo
                    # file that refers to it
                    delete_this_pkg = True
            try:
                cls.delete('pkgsinfo', pathname)
            except FileDeleteError as err:
                errors.append('Error %s when removing %s' % (err, pathname))
            else:
                if delete_this_pkg:
                    try:
                        MunkiRepo.delete('pkgs', pkg_path)
                    except FileDeleteError as err:
                        errors.append('Error %s when removing %s'
                                      % (err, pkg_path))
        if errors:
            raise FileDeleteError(errors)

    @classmethod
    def mass_edit_catalogs(
            cls, pathname_list, catalogs_to_add, catalogs_to_remove, user):
        '''For all pkginfo items in the list, add and remove catalogs'''

        errors = []
        # normalize the catalog lists -- no duplicates; eliminate
        # any items that are in both lists
        normalized_catalogs_to_add = (
            set(catalogs_to_add) - set(catalogs_to_remove))
        normalized_catalogs_to_remove = (
            set(catalogs_to_remove)- set(catalogs_to_add))
        catalogs_to_add = list(normalized_catalogs_to_add)
        catalogs_to_remove = list(normalized_catalogs_to_remove)

        for pathname in pathname_list:
            try:
                plist = cls.read('pkgsinfo', pathname)
            except FileReadError:
                errors.append('Could not read %s' % pathname)
                continue
            if not 'catalogs' in plist:
                plist['catalogs'] = []
            # what will be added?
            new_catalogs = [item for item in catalogs_to_add
                            if item not in plist['catalogs']]
            # what will be removed?
            removed_catalogs = [item for item in catalogs_to_remove
                                if item in plist['catalogs']]
            if new_catalogs or removed_catalogs:
                # add the new ones
                plist['catalogs'].extend(new_catalogs)
                # remove catalogs to remove
                plist['catalogs'] = [item for item in plist['catalogs']
                                     if item not in catalogs_to_remove]
                try:
                    cls.write(plist, 'pkgsinfo', pathname)
                except FileWriteError as err:
                    LOGGER.error('Update failed for %s: %s', pathname, err)
                    errors.append('Error %s when updating %s' % (err, pathname))
                    continue

        if errors:
            raise FileWriteError(errors)

pkgsinfo/templates/pkgsinfo/detail.html
<div class="modal" id="pkginfoItem" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="pkginfoItemLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl modal-dialog-scrollable modal-fullscreen-xl-down">
    <div class="modal-content">
      <div class="modal-header">
          <img src="{{ icon_url }}" class='pkginfo-icon pull-left' height='32' style="margin-top:3px; margin-right:10px;" onerror="this.src='/static/img/GenericPkg.png';"/>
          <h1 class="modal-title fs-5" data-installer-item-path='{{ installer_item_path }}' id="pkginfoItemLabel">{{ pathname }}</h1>
          {% if perms.pkgsinfo.delete_pkginfofile %}
          <button type="button" class="btn btn-danger pull-right" onClick="getPkgRefCount()" data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal">Delete</button>
          {% endif %}
      </div>
      <div role="tabpanel" class="modal-body" >
        <ul class="nav nav-pills mb-3" id="editortabs" role="tablist">
          <li class="nav-item" role="presentation">
            <button class="nav-link active" id="basicstab" data-bs-toggle="tab" data-bs-target="#basicstab-pane" type="button" role="tab" aria-controls="basicstab-pane" aria-selected="false">Basics</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link" id="detailtab" data-bs-toggle="tab" data-bs-target="#detailtab-pane" type="button" role="tab" aria-controls="detailtab-pane" aria-selected="false">Details</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link" id="plisttab" data-bs-toggle="tab" data-bs-target="#plisttab-pane" type="button" role="tab" aria-controls="plisttab-pane" aria-selected="false">Plist</button>
          </li>
        </ul>
        <div class="tab-content" id="item_editor">
          <div class="tab-pane fade show active" id="basicstab-pane" role="tabpanel" aria-labelledby="basicstab" tabindex="0">
              <div id="basics" class="plist-editor"></div>
          </div>
          <div class="tab-pane fade show" id="detailtab-pane" role="tabpanel" aria-labelledby="detailtab" tabindex="0">
              <div id="detail" class="plist-editor"></div>
          </div>
          <div class="tab-pane fade show" id="plisttab-pane" role="tabpanel" aria-labelledby="plisttab" tabindex="0">
              <div id='plist'>{{ plist_text }}</div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        {% if perms.pkgsinfo.change_pkginfofile %}
        <div class='pull-right d-none' id='save_and_cancel'>
          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#cancelEditConfirmationModal">Cancel</button>
          <button type="button" class="btn btn-primary" onClick="savePkginfoItem()">Save</button>
          <button type="button" class="btn btn-primary" onClick="savePkginfoItem('true')">Save and close</button>
        </div>
        {% endif %}
        <div class='pull-right' id='cancel'>
          {% if not perms.pkgsinfo.change_pkginfofile %}<span class="bg-danger">You don't have permissions to make changes here.</span>{% endif %}
          <button type="button" class="btn btn-default" data-bs-dismiss="modal" onClick="cancelEdit()">Cancel</button>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--
Bootstrap modal for confirming pkginfo deletion
-->
<div class="modal" id="deleteConfirmationModal" data-bs-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Delete pkginfo?</h4>
      </div>
      <div class="modal-body">
        <p>Really delete <strong>{{ pathname }}</strong>?</p>
        <p>This action cannot be undone.</p>
        <div id="deleteConfirmationModalInstallerItem" class='d-none'>
            <div class="checkbox pull-right">
                <label>
                    <input type="checkbox" id="delete_pkg" disabled>
                    Also delete installer item
                </label>
            </div>
            <br>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal" onClick="deletePkginfoItem()">Delete</button>
        <button type="button" class="btn btn-default" data-bs-target="#pkginfoItem" data-bs-toggle="modal">Cancel</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--
Bootstrap modal for confirming canceling editing
-->
<div class="modal" id="cancelEditConfirmationModal" data-bs-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Discard your changes?</h4>
      </div>
      <div class="modal-body">
        <p>Really discard your changes to <strong>{{ pathname }}</strong>?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal"  onClick="cancelEdit()">Discard Changes</button>
        <button type="button" class="btn btn-default" data-bs-target="#pkginfoItem" data-bs-toggle="modal">Continue Editing</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--
Bootstrap modal for saving or canceling when loading a different pkginfo
-->
<div class="modal" id="saveOrCancelConfirmationModal" data-bs-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Save your changes?</h4>
      </div>
      <div class="modal-body">
        <p>Save your changes to <strong>{{ pathname }}</strong> before proceeding?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal" onClick="cancelEdit()">Discard Changes</button>
        <button type="button" class="btn btn-success" data-bs-dismiss="modal" onClick="savePkginfoItem()">Save Changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

pkgsinfo/templates/pkgsinfo/pkgsinfo.html
{% extends 'base.html' %}
{% load pkgsinfo_extras %}

{% block extra_style %}
{% load static %}
<link rel="stylesheet" href="{% get_static_prefix %}pkgsinfo/css/pkgsinfo.css" type="text/css" media="all" />
{% endblock extra_style %}

{% block java_script %}
{% load static %}
<script type='text/javascript' src='{% get_static_prefix %}js/typeahead.bundle.js'></script>
<script type='text/javascript' src='{% get_static_prefix %}js/jquery.plisteditor.js'></script>
<script type='text/javascript' src='{% get_static_prefix %}js/plistparser.js'></script>
<script type="text/javascript" charset="utf-8" src="{% get_static_prefix %}js/ace/src-min-noconflict/ace.js"></script>
<script type='text/javascript' src='{% get_static_prefix %}js/mwa_editor_shared.js'></script>
<script type='text/javascript' src='{% get_static_prefix %}pkgsinfo/js/pkgsinfo.js'></script>
<script type='text/javascript' src='{% get_static_prefix %}js/chosen.jquery.min.js'></script>
{% endblock java_script %}

{% block page_title %}Package Info <span class="badge bg-secondary" id="item-count-badge">0</span>{% endblock %}

{% block content %}
<div class="row">
  <div class="col-12">
    <div class="card mb-3">
      <div class="card-body">
        <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
          <div class="btn-group" role="group" aria-label="First group">
            <div class="btn-group" role="group">
              <button type="button" id="catalog_dropdown" class="btn btn-secondary dropdown-toggle" data-value="{{catalog}}" data-bs-toggle="dropdown" aria-expanded="false">
                {{catalog}}
              </button>
              <ul class="dropdown-menu" id="catalog_dropdown_list">
                <li><a class="dropdown-item" href="#">all</a></li>
              </ul>
            </div>
            <button type="button" id="makecatalogs" class="btn btn-primary" onClick="rebuildCatalogs()">Makecatalogs</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#uploadModal">Upload Package</button>
          </div>
          
          <div class="input-group">
            <div class="btn-group" role="group">
              <button type="button" id="massaction_dropdown" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-cog" aria-hidden="true"></i>
              </button>
              <ul class="dropdown-menu" id="massaction_dropdown_list">
                <li><a href="#" class="dropdown-item disabled" id="mass_delete">Delete items…</a></li>
                <li><a href="#" class="dropdown-item disabled" id="mass_edit_catalogs">Edit catalogs…</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> <!-- /row -->

<div class="row">
  <div class="col-12">
    <div class="card mb-3">
      <div class="card-body">
        <table class="table table-striped wraptext" id='list_items'>
          <thead>
            <tr><th>Name</th><th>Version</th></tr>
          </thead>
          <tbody>
              <!-- table is filled via AJAX/JSON calls by DataTables -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- data storage -->
<div id="data_storage"/>

<div id="pkginfo_item_detail"></div>
<!--
Bootstrap modal for mass editing pkginfo items
-->
<div class="modal" id="massEditModal" data-bs-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Edit catalogs for selected items</h4>
      </div>
      <div class="modal-body">
          <p id="massEditModalBodyText">Edit catalogs for the selected pkginfo items:</p>
          <div class="row">
               <div class="col-md-6">
                   <div class="form-group">
                        <label for="catalogs_to_add">Add:</label>
                        <select multiple class="form-select" data-placeholder=" " id='catalogs_to_add'>
                          <option>testing</option>
                        </select>
                   </div>
              </div>
              <div class="col-md-6">
                  <div class="form-group">
                       <label for="catalogs_to_delete">Remove:</label>
                       <select multiple class="form-select" data-placeholder=" " id='catalogs_to_delete'>
                         <option>testing</option>
                       </select>
                  </div>
              </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal" onClick="massEditCatalogs()">Change</button>
        <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--
Bootstrap modal for confirming mass pkginfo deletion
-->
<div class="modal" id="massDeleteConfirmationModal" data-bs-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Delete selected pkginfo items?</h4>
      </div>
      <div class="modal-body">
        <p id="massDeleteConfirmationModalBodyText">Really delete the selected pkginfo items?</p>
        <p>This action cannot be undone.</p>
        <div class="checkbox float-end">
            <label>
                <input type="checkbox" id="mass_delete_pkg">
                Also delete installer items
            </label>
        </div>
        <br>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal" onClick="deletePkginfoList()">Delete</button>
        <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--
Bootstrap modal for showing process progress
-->
<div class="modal" data-bs-backdrop="static" id="process_progress">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="process_progress_title_text">Processing...</h4>
      </div>
      <div class="modal-body">
          <div class="progress">
            <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
              <span class="sr-only">Indeterminate progress</span>
              <div id='process_progress_status_text'>&nbsp;</div>
            </div>
          </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--
Bootstrap modal for errors
-->
<div class="modal" data-bs-backdrop="static" id="errorModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title text-danger">
            <span class="glyphicon glyphicon-alert text-danger" aria-hidden="true"></span>
            <span id="errorModalTitleText">Error</span>
        </h4>
      </div>
      <div class="modal-body">
        <form>
          <p id="errorModalDetailText">An unexpected error occurred.</p>
        </form>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-bs-dismiss="modal">OK</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

<!-- Bootstrap Modal for Upload -->
<div class="modal fade" id="uploadModal" tabindex="-1" aria-labelledby="uploadModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="uploadModalLabel">Upload Package</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="uploadForm" enctype="multipart/form-data">
          <div class="mb-3">
            <label for="fileInput" class="form-label">Select .pkg or .dmg file</label>
            <input class="form-control" type="file" id="fileInput" accept=".pkg,.dmg" required>
          </div>
          <div class="mb-3">
            <label for="subdirectoryPath" class="form-label">Subdirectory Path</label>
            <input class="form-control" type="text" id="subdirectoryPath" placeholder="e.g., apps/firefox/" required>
          </div>
        </form>
        <!-- Upload Progress Bar -->
        <div class="progress mt-2">
          <div id="uploadProgressBar" class="progress-bar progress-bar-striped progress-bar-animated"
              role="progressbar" style="width: 0%;"></div>
        </div>
        <!-- Upload Status Feedback -->
        <div id="uploadAlertContainer" class="mt-3"></div>
      </div>
      <div class="modal-footer">
        <button type="button" id="closeButton" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <button type="button" id="uploadButton" class="btn btn-primary" onclick="uploadPackage()">Upload</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}