api/urls.py
from django.urls import re_path as url
from api.views import ReportsListAPIView, ReportsDetailAPIView, CatalogsListView, CatalogsDetailAPIView, ManifestsListView, ManifestsDetailAPIView, PkgsinfoListView, PkgsinfoDetailAPIView, PkgsListView, PkgsDetailAPIView, IconsListView, IconsDetailAPIView

urlpatterns = [
    url(r'^reports/?$', ReportsListAPIView.as_view(), name="report-list"),
    url(r'^reports/(?P<serial_number>[a-zA-Z0-9]+)$', ReportsDetailAPIView.as_view(), name="report-detail"),
    url(r'^catalogs/?$', CatalogsListView.as_view(), name="catalog-list"),
    url(r'^catalogs/(?P<filepath>.*$)', CatalogsDetailAPIView.as_view(), name="catalog-detail"),
    url(r'^manifests/?$', ManifestsListView.as_view(), name="manifest-list"),
    url(r'^manifests/(?P<filepath>.*$)', ManifestsDetailAPIView.as_view()),
    url(r'^pkgsinfo/?$', PkgsinfoListView.as_view(), name="pkgsinfo-list"),
    url(r'^pkgsinfo/(?P<filepath>.*$)', PkgsinfoDetailAPIView.as_view(), name="pkgsinfo-detail"),
    url(r'^pkgs/?$', PkgsListView.as_view(), name="pkgs-list"),
    url(r'^pkgs/(?P<filepath>.*$)', PkgsDetailAPIView.as_view(), name="pkgs-download"),
    url(r'^icons/?$', IconsListView.as_view(), name="icon-list"),
    url(r'^icons/(?P<filepath>.*$)', IconsDetailAPIView.as_view(), name="icon-download"),
]

manifests/urls.py
from django.urls import re_path as url
import manifests.views

urlpatterns = [
    url(r'^$', manifests.views.index, name='manifests'),
    url(r'^__get_manifest_list_status$', manifests.views.status),
    url(r'^(?P<manifest_path>.*$)', manifests.views.index)
]

munkiwebadmin/urls.py
from django.urls import re_path as url
from django.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from  django.contrib.auth.views import LoginView, logout_then_login
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

from django.contrib import admin
admin.autodiscover()

import os
try:
	BASE_DIR = settings.BASE_DIR
except:
	BASE_DIR = ""
      
try:
	REPO_MANAGEMENT_ONLY = settings.REPO_MANAGEMENT_ONLY
except:
	REPO_MANAGEMENT_ONLY = False

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^oauth2/', include('django_auth_adfs.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^manifests/', include('manifests.urls')),
    url(r'^reports/', include('reports.urls')),
    url(r'^catalogs/', include('catalogs.urls')),
    url(r'^pkgsinfo/', include('pkgsinfo.urls')),
    url(r'^icons/', include('icons.urls')),
    url(r'^inventory/', include('inventory.urls')),
    url(r'^santa/', include('santa.urls')),
    url(r'^makecatalogs/', include('process.urls')),
]

if REPO_MANAGEMENT_ONLY:
    urlpatterns.append(url(r'^$', RedirectView.as_view(url='/manifests/')))
else:
    urlpatterns.append(url(r'^$', RedirectView.as_view(url='/reports/')))

# comment out the following if you are serving
# static files a different way
urlpatterns += staticfiles_urlpatterns()

# debug/development serving MEDIA files (icons)
try:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
except django.core.exceptions.ImproperlyConfigured:
    print("**** MEDIA_URL or MEDIA_ROOT missing from settings.py       ****")
    print("**** copy MEDIA_URL or MEDIA_ROOT from settings_template.py ****")
    raise

manifests/models.py
"""
manifests/models.py
"""
from django.db import models

class ManifestFile(models.Model):
    '''Placeholder so we get permissions entries in the admin database'''
    pass

manifests/views.py
"""
manifests/views.py
"""
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from api.models import MunkiRepo, FileDoesNotExistError, FileReadError
from process.models import Process

import json
import logging
import plistlib

LOGGER = logging.getLogger('munkiwebadmin')

def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

def status(request):
    '''Returns status of long-running process'''
    LOGGER.debug('got status request for manifests_list_process')
    status_response = {}
    processes = Process.objects.filter(name='manifests_list_process')
    if processes:
        # display status from one of the active processes
        # (hopefully there is only one!)
        process = processes[0]
        status_response['statustext'] = process.statustext
    else:
        status_response['statustext'] = 'Processing'
    return HttpResponse(json.dumps(status_response),
                        content_type='application/json')

@login_required
def index(request, manifest_path=None):
    '''Returns manifest list or detail'''
    if manifest_path and is_ajax(request):
        # return manifest detail
        if request.method == 'GET':
            LOGGER.debug("Got read request for %s", manifest_path)
            key_list = {'catalogs', 'included_manifests', 'featured_items', 'managed_installs', 'managed_uninstalls', 'managed_updates', 'optional_installs'}
            try:
                plist = MunkiRepo.read('manifests', manifest_path)
                for key in key_list:
                    if key not in plist:
                        plist[key] = []
                plist = plistlib.dumps(plist).decode()
            except (FileDoesNotExistError, FileReadError) as err:
                return HttpResponse(
                    json.dumps({'result': 'failed',
                                'exception_type': str(type(err)),
                                'detail': str(err)}),
                    content_type='application/json', status=404)
            context = {'plist_text': plist,
                       'pathname': manifest_path}
            return render(request, 'manifests/detail.html', context=context)
        if request.method == 'POST':
            return HttpResponse(
                json.dumps({'result': 'failed',
                            'exception_type': 'MethodNotSupported',
                            'detail': 'POST/PUT/DELETE should use the API'}),
                content_type='application/json', status=404)
    # return list of available manifests
    LOGGER.debug("Got index request for manifests")
    context = {'page': 'manifests',
               'manifest_name': manifest_path}
    return render(request, 'manifests/manifests.html', context=context)

manifests/templates/manifests/detail.html
<div class="modal" id="manifestItems" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="manifestItemsLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable modal-xl modal-fullscreen-xl-down">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="manifestItemsLabel">{{ pathname }}</h1>
        <div class='' id='delete_btn'>
        {% if perms.manifests.delete_manifestfile %}
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal">Delete</button>
        {% endif %}
        {% if perms.manifests.change_manifestfile %}
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#copyManifestModal">Duplicate</button>
        {% endif %}
        </div>
      </div>
      <div role="tabpanel" class="modal-body" >
        <ul class="nav nav-pills mb-3" id="editortabs" role="tablist">
          <li class="nav-item" role="presentation">
            <button class="nav-link active" id="basicstab" data-bs-toggle="tab" data-bs-target="#basicstab-pane" type="button" role="tab" aria-controls="basicstab-pane" aria-selected="false">Basics</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link" id="detailtab" data-bs-toggle="tab" data-bs-target="#detailtab-pane" type="button" role="tab" aria-controls="detailtab-pane" aria-selected="false">Details</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link" id="plisttab" data-bs-toggle="tab" data-bs-target="#plisttab-pane" type="button" role="tab" aria-controls="plisttab-pane" aria-selected="false">Plist</button>
          </li>
        </ul>
        <div class="tab-content" id="item_editor">
          <div class="tab-pane fade show active" id="basicstab-pane" role="tabpanel" aria-labelledby="basicstab" tabindex="0">
              <div id="basics" class="plist-editor"></div>
          </div>
          <div class="tab-pane fade show" id="detailtab-pane" role="tabpanel" aria-labelledby="detailtab" tabindex="0">
              <div id="detail" class="plist-editor"></div>
          </div>
          <div class="tab-pane fade show" id="plisttab-pane" role="tabpanel" aria-labelledby="plisttab" tabindex="0">
              <div id='plist'>{{ plist_text }}</div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        {% if perms.manifests.change_manifestfile %}
        <div class='pull-right d-none' id='save_and_cancel'>
          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#cancelEditConfirmationModal">Cancel</button>
          <button type="button" class="btn btn-success" onClick="saveManifestItem()">Save</button>
        </div>
        {% endif %}
        <div class='pull-right' id='cancel'>
          {% if not perms.manifests.change_manifestfile %}<span class="bg-danger">You don't have permissions to make changes here.</span>{% endif %}
          <button type="button" class="btn btn-default" data-bs-dismiss="modal" onClick="cancelEdit()">Cancel</button>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--
Bootstrap modal for confirming manifest deletion
-->
<div class="modal" id="deleteConfirmationModal" data-bs-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Delete manifest?</h4>
      </div>
      <div class="modal-body">
        <p>Really delete <strong>{{ pathname }}</strong>?</p>
        <p>This action cannot be undone.</p>
        <br>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal"  onClick="deleteManifestItem('{{ pathname }}')">Delete</button>
        <button type="button" class="btn btn-default" data-bs-target="#manifestItems" data-bs-toggle="modal">Cancel</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--
Bootstrap modal for confirming canceling editing
-->
<div class="modal" id="cancelEditConfirmationModal" data-bs-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Discard your changes?</h4>
      </div>
      <div class="modal-body">
        <p>Really discard your changes to <strong>{{ pathname }}</strong>?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal"  onClick="cancelEdit()">Discard Changes</button>
        <button type="button" class="btn btn-default" data-bs-target="#manifestItems" data-bs-toggle="modal">Continue Editing</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--
Bootstrap modal for saving or canceling when loading a different manifest
-->
<div class="modal" id="saveOrCancelConfirmationModal" data-bs-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Save your changes?</h4>
      </div>
      <div class="modal-body">
        <p>Save your changes to <strong>{{ pathname }}</strong> before proceeding?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal"  onClick="cancelEdit()">Discard Changes</button>
        <button type="button" class="btn btn-success" data-bs-dismiss="modal" onClick="saveManifestItem()">Save Changes</button>
        <button type="button" class="btn btn-default" data-bs-dismiss="modal">Continue Editing</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--
Bootstrap modal for duplicating a manifest
-->
<div class="modal" id="copyManifestModal" data-bs-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Duplicate manifest</h4>
      </div>
      <div class="modal-body">
        <form id="manifest-duplicate-form">
          <div class="form-group">
            <label for="recipient-name" class="control-label">New manifest name:</label>
            <input type="text" class="form-control" id="manifest-copy-name">
          </div>
        </form>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
          <button type="button" data-copy="manifest" class="btn btn-primary">Duplicate</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

manifests/templates/manifests/manifests.html
{% extends 'base.html' %}

{% block extra_style %}
{% load static %}
<link rel="stylesheet" href="{% get_static_prefix %}manifests/css/manifests.css" type="text/css" media="all" />
{% endblock extra_style %}

{% block java_script %}
{% load static %}
<script type='text/javascript' src='{% get_static_prefix %}js/typeahead.bundle.js'></script>
<script type='text/javascript' src='{% get_static_prefix %}js/jquery.plisteditor.js'></script>
<script type='text/javascript' src='{% get_static_prefix %}js/plistparser.js'></script>
<script type="text/javascript" charset="utf-8" src="{% get_static_prefix %}js/ace/src-min-noconflict/ace.js"></script>
<script type='text/javascript' src='{% get_static_prefix %}js/mwa_editor_shared.js'></script>
<script type='text/javascript' src='{% get_static_prefix %}manifests/js/manifests.js'></script>
{% endblock java_script %}

{% block body_tag %}
<body {% if manifest_name %}onLoad="getManifestItem('{{manifest_name}}')"{% endif %}>
{% endblock %}

{% block page_title %}Manifests <span class="badge bg-secondary" id="item-count-badge">0</span>{% endblock %}

{% block content %}
<div class="row">
  <div class="col-12">
    <div class="card mb-3">
      <div class="card-body">
        <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
          <div class="btn-group" role="group" aria-label="First group">
            <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#searchManifestModal">
              Search manifests
            </button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#newManifestModal">
              New manifest
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> <!-- /row -->

<div class="row">
  <div class="col-12">
    <div class="card mb-3">
      <div class="card-body">
        <table class="table table-striped wraptext" id='list_items'>
          <thead>
            <tr><th>Name</th></tr>
          </thead>
          <tbody>
              <!-- table is filled via AJAX/JSON calls by DataTables -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<!-- data storage -->
<div id="data_storage"></div>

<div id="manifest_detail"></div>
<!--
Bootstrap modal for showing progress
-->
<div class="modal" data-bs-backdrop="static" id="process_progress">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="process_progress_title_text">Processing...</h4>
      </div>
      <div class="modal-body">
          <div class="progress">
            <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
              <span class="sr-only">Indeterminate progress</span>
              <div id='process_progress_status_text'>&nbsp;</div>
            </div>
          </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>
<!--
Bootstrap modal for creating manifests
-->
<div class="modal" data-bs-backdrop="static" id="newManifestModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Create new manifest</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="new-manifest-name" class="control-label">Manifest name:</label>
            <input type="text" class="form-control" id="new-manifest-name">
          </div>
        </form>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
          <button type="button" data-new="manifest" class="btn btn-primary">Create</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>
<!--
Bootstrap modal for searching inside manifests
-->
<div class="modal" data-bs-backdrop="static" id="searchManifestModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Search</h4>
      </div>
      <div class="modal-body">
        <form id='search_parameters'>
          <div class="form-group">
            <label for="manifest-search-text" class="control-label">Search text:</label>
            <input type="text" class="form-control" id="manifest-search-text" name="search_text">
          </div>
          <div class="form-group">
              <label for="manifest-section-choice" class="control-label">Manifest section:</label>
              <select class="form-control" id="manifest-search-section" name="search_section">
                  <option value='managed_installs'>Managed Installs</option>
                  <option value='managed_uninstalls'>Managed Uninstalls</option>
                  <option value='managed_updates'>Managed Updates</option>
                  <option value='optional_installs'>Optional Installs</option>
                  <option value='included_manifests'>Included Manifests</option>
                  <option value='featured_items'>Featured Items</option>
                  <option value='catalogs'>Catalogs</option>
              </select>
        </div>
        </form>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-primary" id='manifest_search_btn'>Search</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>
<!--
Bootstrap modal for errors
-->
<div class="modal" data-bs-backdrop="static" id="errorModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title text-danger">
            <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
            <span id="errorModalTitleText">Error</span>
        </h4>
      </div>
      <div class="modal-body">
        <form>
          <p id="errorModalDetailText">An unexpected error occurred.</p>
        </form>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-bs-dismiss="modal">OK</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>
{% endblock content %}